name: second-me
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24.0
  - cmake>=3.27.0
  - pybind11>=2.11.0
  - pytest>=7.0.0
  - pip:
    - flask>=2.3.0
    - requests>=2.31.0
    - langchain>=0.0.267
    - chromadb>=0.4.13
    - pytest>=7.4.0
    - ruff>=0.0.290
    - graphrag==1.2.1.dev27
    - python-dotenv>=1.0.0
